services:
  backend:
    build:
      target: development
    volumes:
      - ./backend:/app
    environment:
      UV_PROJECT_ENVIRONMENT: /venv
      DEV: "true"
      POSTGRES_HOST: db
    command: uv run app/main.py

  frontend:
    build:
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_TARGET=http://backend:8000
    command: npm run dev
