services:
  db:
    image: postgres:16-alpine
    container_name: substrack-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-substrack}
    volumes:
      - substrack-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: substrack-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_TYPE: postgres
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-substrack}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: substrack-frontend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  substrack-db:
